import Head from "next/head";
import Layout from "@/components/common/Layout";
import Masonry from "@/components/main/Masonry";

export default function Home() {
  return (
    <>
      <Head>
        <title>filosophy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Masonry />
      </Layout>
    </>
  );
}
